### ISSUE TITLE
Rename 'schemaConfiguration' to 'config'

### ISSUE THREAD

**Issue by kennardconsulting** [AmitsBizruntime/MetawidetA2#1]
In https://github.com/AmitsBizruntime/MetawidetA2/blob/master/metawidget-using-A2_webpack/src/app/app.component.html can we make:

    <metawidget [(schemaConfiguration)]="config" [(model)]="model" ></metawidget>

be:

    <metawidget [(config)]="config" [(model)]="model" ></metawidget>

**Comment by VivekParanthaman** [comment]
@kennardconsulting 👍 : Have it changed, from "schemaConfiguration" to be "config"

**Comment by kennardconsulting** [comment]
Under...

https://github.com/AmitsBizruntime/MetawidetA2/blob/master/metawidget-using-A2_webpack/src/app/app.component.html

...it still references `[(schemaConfiguration)]`? This should be `[(config)]="config"`

**Comment by VivekParanthaman** [comment]
Was just git push issue, have rectified it..
