### ISSUE TITLE
Click binding needs to refer to object

### ISSUE THREAD

**Issue by kennardconsulting** [AmitsBizruntime/MetawidetA2#2]
Re: https://github.com/AmitsBizruntime/MetawidetA2/blob/master/metawidget-using-A2_webpack/src/app/app.component.ts

I see `save()` is under a separate object to `model` (is not under any object, in fact)...

    function save() { ... }
    var model = { ... }

...and yet is still defined in the same JSON Schema alongside `firstname`, `lastName` etc. I don't think this can work. One JSON Schema cannot refer to two objects.

Can you please move `save()` under a separate `actions` object...

    var actions = { save: function() { ... }}
    var model = { ... }

Then inspect the object with a separate Metawidget (possibly nested, or possibly a sibling of the existing Metawidget) that just uses a default `PropertyTypeInspector` to discover the function. For example:

    <div class="col-md-12">
         <metawidget [(model)]="model" [(config)]="config"></metawidget>
         <metawidget [(model)]="actions"></metawidget>
    </div>

You will have to modify your `(click)` binding to include the actions object (e.g. `actions.save`).

Then remove `save` from the JSON Schema.

**Comment by VivekParanthaman** [comment]
Have made the necessary changes on to the A2WidgetProcessor. 
`
<metawidget #meta1 [(config)]="config" [(model)]="model" ></metawidget>
<metawidget #meta2 [(model)]="actions" ></metawidget>`

are two variations showing the difference in config-rendering & action-rendering.
