### ISSUE TITLE
Upgrade to Angular 4 and create a publishable module for NPM

### ISSUE THREAD

**Issue by SeanFarrow** [AmitsBizruntime/MetawidetA2#3]
It would be nice if this were a stand-alone module available on npm and was upgraded to ng4.
I'm happy to help do this if needed.
But am not sure what the dynamic service does.
Kind regards
Sean.

**Comment by SeanFarrow** [comment]
Hi,

I won’t be needing this as we’re using reactive forms.

**Comment by SeanFarrow** [comment]
Hi, We're looking at this again, what's the architecture of the components as it's unclear?

**Comment by VivekParanthaman** [comment]
It follows the below architecture without fail, the code is only a prototype. Not a stable one. Would appreciate anyone to contribute..
http://metawidget.sourceforge.net/doc/reference/en/html/ch02.html

**Comment by SeanFarrow** [comment]
Ok, what does the dynamic service do, it seems like it doesn’t need to be there?
Cheers
Sean.

**Comment by VivekParanthaman** [comment]
Which is used to compile the components & its generated templates
dynamically.

**Comment by VivekParanthaman** [comment]
https://www.npmjs.com/package/metawidget

Npm package is released by Richard here.. for A2
